// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConsistencySvg: typeof import('./.vitepress/vitepress/components/globals/design/consistency-svg.vue')['default']
    ControllabilitySvg: typeof import('./.vitepress/vitepress/components/globals/design/controllability-svg.vue')['default']
    Dark: typeof import('./.vitepress/vitepress/components/icons/dark.vue')['default']
    DesignGuide: typeof import('./.vitepress/vitepress/components/globals/design-guide.vue')['default']
    EfficiencySvg: typeof import('./.vitepress/vitepress/components/globals/design/efficiency-svg.vue')['default']
    FeedbackSvg: typeof import('./.vitepress/vitepress/components/globals/design/feedback-svg.vue')['default']
    Icons: typeof import('./.vitepress/vitepress/components/globals/icons.vue')['default']
    IRiExternalLinkLine: typeof import('~icons/ri/external-link-line')['default']
    IRiTranslate2: typeof import('~icons/ri/translate2')['default']
    Light: typeof import('./.vitepress/vitepress/components/icons/light.vue')['default']
    VpApp: typeof import('./.vitepress/vitepress/components/vp-app.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
    VpHamburger: typeof import('./.vitepress/vitepress/components/navbar/vp-hamburger.vue')['default']
    VpLink: typeof import('./.vitepress/vitepress/components/common/vp-link.vue')['default']
    VpMenu: typeof import('./.vitepress/vitepress/components/navbar/vp-menu.vue')['default']
    VpMenuLink: typeof import('./.vitepress/vitepress/components/navbar/vp-menu-link.vue')['default']
    VpNav: typeof import('./.vitepress/vitepress/components/vp-nav.vue')['default']
    VpNavbar: typeof import('./.vitepress/vitepress/components/vp-navbar.vue')['default']
    VpNotFound: typeof import('./.vitepress/vitepress/components/vp-not-found.vue')['default']
    VpSearch: typeof import('./.vitepress/vitepress/components/navbar/vp-search.vue')['default']
    VpSocialLink: typeof import('./.vitepress/vitepress/components/navbar/vp-social-link.vue')['default']
    VpSocialLinks: typeof import('./.vitepress/vitepress/components/navbar/vp-social-links.vue')['default']
    VpSwitch: typeof import('./.vitepress/vitepress/components/common/vp-switch.vue')['default']
    VpThemeToggler: typeof import('./.vitepress/vitepress/components/navbar/vp-theme-toggler.vue')['default']
    VpTranslation: typeof import('./.vitepress/vitepress/components/navbar/vp-translation.vue')['default']
  }
}

export {}
